# Generated by Django 5.2.5 on 2025-08-13 09:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDatabaseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_slug', models.CharField(help_text="URL-safe tenant identifier like 'techcorp', 'microsoft'", max_length=50, unique=True)),
                ('company_name', models.CharField(help_text="Full company name like 'TechCorp Inc.'", max_length=200)),
                ('database_name', models.CharField(help_text="Physical database name like 'techcorp_compliance_db'", max_length=100)),
                ('database_user', models.CharField(max_length=50)),
                ('database_password', models.TextField(help_text='Encrypted password')),
                ('database_host', models.CharField(default='localhost', max_length=100)),
                ('database_port', models.CharField(default='5432', max_length=10)),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant_database_info',
                'ordering': ['tenant_slug'],
            },
        ),
    ]
