# Generated by Django 5.2.5 on 2025-08-14 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='tenant_slug',
            field=models.CharField(help_text="URL-safe tenant identifier like 'techcorp', 'microsoft'", max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='tenant_slug must be 3–50 chars: lowercase letters, numbers, hyphens', regex='^[a-z0-9-]{3,50}$')]),
        ),
    ]
