# Generated by Django 5.2.5 on 2025-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdatabaseinfo_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='status',
            field=models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('PROVISIONING_FAILED', 'Provisioning Failed')], default='ACTIVE', max_length=20),
        ),
    ]
